// TODO This code is generated by AI and NOT reviewed yet!
package org.jboss.as.quickstarts.kitchensink.data;

import org.jboss.as.quickstarts.kitchensink.model.Member;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;

@Repository
public interface MemberRepository extends JpaRepository<Member, Long> {

    // Derived query to find a member by email
    Member findByEmail(String email);

    // Custom method to find all members ordered by name
    @Transactional(readOnly = true)
    List<Member> findAllByOrderByNameAsc();
}
