version: '3'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - mongodb_data:/data/db
      - mongodb_data:/data/configdb
      - ./mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    expose:
      - "27017"
    ports:
      - "27017:27017"
    networks:
      - kitchensink_migrated_network
    command:
      - --auth
  spring_boot_server:
    build: .
    ports:
      - "8080:8080"
    networks:
      - kitchensink_migrated_network
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - mongodb

volumes:
  mongodb_data:

networks:
  kitchensink_migrated_network:
